### ISSUE TITLE
READMEの問題: index.js:683 Uncaught Error: MICROCMS_SERVICE_DOMAIN is required

### ISSUE THREAD

**Issue by kazurayam** [nextjs-microcms-book/nextjs-website-sample#33]
このレポジトリをcloneした。READEにこう書いてあった。

```
## 開発環境の立ち上げ方法
'''bash
npm run dev
'''
コマンドラインにて上記コマンドを入力後、[http://localhost:3000](http://localhost:3000)にアクセスします。
```

READMEのこの記述にしたがって
npm run devし、ブラウザでアクセスした。そしたらエラ〜が発生した。

```
$ npm run dev

> my-next-project@0.1.0 dev
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Port 3001 is in use, trying 3002 instead.
   ▲ Next.js 14.1.4
   - Local:        http://localhost:3002

 ✓ Ready in 2.8s
 ○ Compiling / ...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 ✓ Compiled / in 4.9s (679 modules)
 ⨯ app/_libs/microcms.ts (28:8) @ eval
 ⨯ Error: MICROCMS_SERVICE_DOMAIN is required
    at eval (./app/_libs/microcms.ts:13:11)
    at (rsc)/./app/_libs/microcms.ts (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/app/page.js:401:1)
    at __webpack_require__ (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:11:76)
    at (rsc)/./app/page.tsx (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/app/page.js:445:1)
    at Function.__webpack_require__ (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
  26 |
  27 | if (!process.env.MICROCMS_SERVICE_DOMAIN) {
> 28 |   throw new Error('MICROCMS_SERVICE_DOMAIN is required');
     |        ^
  29 | }
  30 |
  31 | if (!process.env.MICROCMS_API_KEY) {
 ⨯ app/_libs/microcms.ts (28:8) @ eval
 ⨯ Error: MICROCMS_SERVICE_DOMAIN is required
    at eval (./app/_libs/microcms.ts:13:11)
    at (rsc)/./app/_libs/microcms.ts (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/app/page.js:401:1)
    at __webpack_require__ (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:11:76)
    at (rsc)/./app/page.tsx (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/app/page.js:445:1)
    at Function.__webpack_require__ (/Users/kazuakiurayama/tmp/nextjs-website-sample/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
digest: "186965615"
```

書籍のSection 5-3-1 「メンバーページにmicoroCMSを組み込んでみよう/事前準備をしよう/環境変数の設定」に.env.localファイルの準備の仕方が書いてあった。私はこの準備をまだしていなかった。だから上記のエラ〜が発生した。それはいい。

しかしREADME.mdの記述が不十分なのではないか？

「コマンドラインにて上記コマンドを入力後、[http://localhost:3000](http://localhost:3000)にアクセスします。するといろいろエラーが発生します。その解決方法は本文を参照願います。」

とするとか。

**Comment by shibe97** [comment]
@kazurayam こちらについてもREADMEに追記させていただきます。

**Comment by shibe97** [comment]
#34 にて修正。
