### ISSUE TITLE
HubSpotにPOSTしようとして失敗した 405 Method Not Allowed

### ISSUE THREAD

**Issue by kazurayam** [nextjs-microcms-book/nextjs-website-sample#35]
第９章を写経した。HubSpotに私のアカウントを作り、フォームを作った。section 9-2-4のcontact.tsを写した。

- https://github.com/kazurayam/nextjs-microcms-book/blob/issue3/my-next-project/app/_actions/contact.ts

VSCodeのターミナルで `$ npm run dev`した。ブラウザで http://localhost:3000/contact を開いた。お問い合わせフォームが表示されたのでデータを入力して送信ボタンを押した。そうしたらエラーメッセージが応答された。

ターミナルにExceptionのStack Traceが出力された。

```
✓ Compiled in 707ms (631 modules)
{ status: '', message: '' }
SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5419:19)
    at successSteps (node:internal/deps/undici/undici:5390:27)
    at fullyReadBody (node:internal/deps/undici/undici:1501:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5399:7)
    at async createContactData (webpack-internal:///(action-browser)/./app/_actions/contact.ts:97:9)
    at async /Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:406
    at async t2 (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:6412)
    at async rS (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1369)
    at async doRender (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:1378:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:1539:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:1447:28)
    at async DevServer.renderPageComponent (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:1844:24)
    at async DevServer.renderToResponseImpl (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:1882:32)
    at async DevServer.pipeImpl (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/next-server.js:269:17)
    at async DevServer.handleRequestImpl (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/base-server.js:791:17)
    at async /Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/kazuakiurayama/github/nextjs-microcms-book/my-next-project/node_modules/next/dist/server/lib/start-server.js:140:13)

```

このメッセージを読むと、HubSpotからJSONではなくHTMLが応答されたようだ。しかしどんなHTMLなのか、このメッセージからはわからない。そこでブラウザでアドレスバーに

https://api.hsforms.com/submissions/v3/integration/submit/${process.env.HUBSPOT_PORTAL_ID}/${process.env.HUBSPOT_FORM_ID}

（ただし環境変数の値を具体的な値に置換した文字列）をタイプインして問い合わせた。そうしたらこんな画面が表示された。

![image](https://github.com/user-attachments/assets/8ae0d3c7-c5e8-459a-8fb3-8fc46750f4ec)

HubSpotがPOST命令を受け付けられない、と言っている。はてな？

”HubSpot Form 405 METHOD NOT ALLOWED”とキー指定してググった。いくつか引っかかる記事もあった。しかし私の問題の答えに辿り着くことは容易でなさそうだ。

**Comment by kazurayam** [comment]
わたしの感想：

「かんたんモダンweb制作入門」本の第８章まではとてもスムーズだった。しかし第９章は「かんたん」ではない。上記のようなエラーが発生すると手も足も出ない。HubSpotは私にとって荷が重い。formrunを試そうと思う。

**Comment by kazurayam** [comment]
第９章のお問い合わせページをHubSpotでなくformrunで作ることを試みて成功しました。Qiitaに投稿しました。

[React＋Next.jsアプリのお問い合わせページをフォーム作成ツール formrun で作ってみた](https://qiita.com/kazurayam/items/8f74a37c9f33b0a3fb6e)
